### ISSUE TITLE
컨트롤러, 엔티티, DTO, 간단한 Repository 생성

### ISSUE THREAD

**Issue by jgm0327** [jgm0327/ThinkIT-#1]
* [x] 개념, 문제를 위한 컨트롤러 생성
* [x] 개념, 문제를 위한 엔티티 생성
* [x] 데이터 통신을 위한 DTO 생성
* [x] 엔티티들을 위한 Repository 생성

**Comment by jhchoi57** [comment]
ㅋㅋㅋㅋ 새로 팠네요

**Comment by jgm0327** [comment]
걸렸네....
